// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okochwitqzmybycukiqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rb2Nod2l0cXpteWJ5Y3VraXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczODE4MjEsImV4cCI6MjA3Mjk1NzgyMX0.ylbGm0-wtg-uGxnjXTFkQVnfP-Yn46iMKSx6om80fI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});